/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameMgr from "./Scripts/GameMgr"
import QpListAdBox from "./QpAPI/AdView/QpListAdBox"
import QpListAdView from "./QpAPI/AdView/QpListAdView"
import ButtonAnim from "./View/ButtonAnim"
import Export1AdView from "./View/GameView/Export1AdView"
import Export2AdView from "./View/GameView/Export2AdView"
import Export3AdView from "./View/GameView/Export3AdView"
import QpRandomJump from "./QpAPI/AdView/QpRandomJump"
import QpRdListAdBox from "./QpAPI/AdView/QpRdListAdBox"
import QpShakeAd3View from "./QpAPI/AdView/QpShakeAd3View"
import FriendExport from "./View/GameView/FriendExport"
import QpShakeAd2View from "./QpAPI/AdView/QpShakeAd2View"
import QpBannerVIew from "./QpAPI/AdView/QpBannerVIew"
import GameOverFailView from "./View/GameView/GameOverFailView"
import CoinSubView from "./Scripts/MyGameView/CoinSubView"
import ExamineCheck from "./Scripts/MyGameView/ExamineCheck"
import GameOverWinView from "./View/GameView/GameOverWinView"
import Controller from "./Scripts/MyGameView/Controller"
import Rocker from "./Scripts/GameCore/Rocker"
import BtnPanel from "./Scripts/MyGameView/BtnPanel"
import GameStep from "./Scripts/MyGameView/GameStep"
import TwinkleSprite from "./View/TwinkleSprite"
import AlphaBreathingAni from "./View/AlphaBreathingAni"
import InGameView from "./View/GameView/InGameView"
import KdBannerView from "./Scripts/MyGameView/KdBannerView"
import FirstViewAd from "./View/GameView/FirstViewAd"
import MainGameView from "./View/GameView/MainGameView"
import SelectHero from "./View/GameView/SelectHero"
import TutorialView from "./Scripts/MyGameView/TutorialView"
import LoadingView from "./View/LoadingView/LoadingView"
import OppoNativeAdView from "./View/OPPO/OppoNativeAdView"
import TmBannerAdView from "./TmAPI/AdView/TmBannerAdView"
import TmListAdBox from "./TmAPI/AdView/TmListAdBox"
import TmListAdView from "./TmAPI/AdView/TmListAdView"
import TmSingleAdView from "./TmAPI/AdView/TmSingleAdView"
import TmShakeAdView from "./TmAPI/AdView/TmShakeAdView"
import TmSidePopAdView from "./TmAPI/AdView/TmSidePopAdView"
import TipsView from "./View/TipsView/TipsView"
import UniversalBottomZone from "./View/Common/UniversalBottomZone"
import VivoNativeAdView from "./View/VIVO/VivoNativeAdView"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1334;
    static height:number=750;
    static scaleMode:string="fixedheight";
    static screenMode:string="horizontal";
    static alignV:string="middle";
    static alignH:string="center";
    static startScene:any="Main.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("Scripts/GameMgr.ts",GameMgr);
        reg("QpAPI/AdView/QpListAdBox.ts",QpListAdBox);
        reg("QpAPI/AdView/QpListAdView.ts",QpListAdView);
        reg("View/ButtonAnim.ts",ButtonAnim);
        reg("View/GameView/Export1AdView.ts",Export1AdView);
        reg("View/GameView/Export2AdView.ts",Export2AdView);
        reg("View/GameView/Export3AdView.ts",Export3AdView);
        reg("QpAPI/AdView/QpRandomJump.ts",QpRandomJump);
        reg("QpAPI/AdView/QpRdListAdBox.ts",QpRdListAdBox);
        reg("QpAPI/AdView/QpShakeAd3View.ts",QpShakeAd3View);
        reg("View/GameView/FriendExport.ts",FriendExport);
        reg("QpAPI/AdView/QpShakeAd2View.ts",QpShakeAd2View);
        reg("QpAPI/AdView/QpBannerVIew.ts",QpBannerVIew);
        reg("View/GameView/GameOverFailView.ts",GameOverFailView);
        reg("Scripts/MyGameView/CoinSubView.ts",CoinSubView);
        reg("Scripts/MyGameView/ExamineCheck.ts",ExamineCheck);
        reg("View/GameView/GameOverWinView.ts",GameOverWinView);
        reg("Scripts/MyGameView/Controller.ts",Controller);
        reg("Scripts/GameCore/Rocker.ts",Rocker);
        reg("Scripts/MyGameView/BtnPanel.ts",BtnPanel);
        reg("Scripts/MyGameView/GameStep.ts",GameStep);
        reg("View/TwinkleSprite.ts",TwinkleSprite);
        reg("View/AlphaBreathingAni.ts",AlphaBreathingAni);
        reg("View/GameView/InGameView.ts",InGameView);
        reg("Scripts/MyGameView/KdBannerView.ts",KdBannerView);
        reg("View/GameView/FirstViewAd.ts",FirstViewAd);
        reg("View/GameView/MainGameView.ts",MainGameView);
        reg("View/GameView/SelectHero.ts",SelectHero);
        reg("Scripts/MyGameView/TutorialView.ts",TutorialView);
        reg("View/LoadingView/LoadingView.ts",LoadingView);
        reg("View/OPPO/OppoNativeAdView.ts",OppoNativeAdView);
        reg("TmAPI/AdView/TmBannerAdView.ts",TmBannerAdView);
        reg("TmAPI/AdView/TmListAdBox.ts",TmListAdBox);
        reg("TmAPI/AdView/TmListAdView.ts",TmListAdView);
        reg("TmAPI/AdView/TmSingleAdView.ts",TmSingleAdView);
        reg("TmAPI/AdView/TmShakeAdView.ts",TmShakeAdView);
        reg("TmAPI/AdView/TmSidePopAdView.ts",TmSidePopAdView);
        reg("View/TipsView/TipsView.ts",TipsView);
        reg("View/Common/UniversalBottomZone.ts",UniversalBottomZone);
        reg("View/VIVO/VivoNativeAdView.ts",VivoNativeAdView);
    }
}
GameConfig.init();