/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LayaView=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.View {
    export class LoadingUI extends Laya.View {
        public static  uiView:any ={"type":"View","props":{"zOrder":10,"width":1334,"top":0,"right":0,"mouseThrough":false,"left":0,"height":750,"bottom":0},"compId":2,"child":[{"type":"Image","props":{"skin":"LoadingView/zhuyebeijing.jpg","right":0,"name":"BG","left":0,"bottom":0},"compId":11},{"type":"Image","props":{"width":415,"top":158,"skin":"LoadingView/logo.png","pivotY":70,"pivotX":208,"name":"Logo","height":140,"centerX":0},"compId":12},{"type":"Image","props":{"skin":"LoadingView/loading.png","centerX":0,"bottom":99},"compId":27},{"type":"Image","props":{"zOrder":0,"skin":"LoadingView/jiazaijindu1.png","pivotY":22,"name":"ProcessBarBg","centerX":0,"bottom":57},"compId":5,"child":[{"type":"Image","props":{"y":2,"x":3,"width":456,"skin":"LoadingView/jiazaijindu2.png","sizeGrid":"0,45,0,531","name":"ProcessBar"},"compId":9}]},{"type":"Script","props":{"y":0,"x":0,"runtime":"View/LoadingView/LoadingView.ts"},"compId":7}],"loadList":["LoadingView/zhuyebeijing.jpg","LoadingView/logo.png","LoadingView/loading.png","LoadingView/jiazaijindu1.png","LoadingView/jiazaijindu2.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(LoadingUI.uiView);
        }
    }
    REG("ui.View.LoadingUI",LoadingUI);
}